fa_dc_offset_removal:
  ros__parameters:
    input_topic: "audio/sample_format/mic"
    output_topic: "audio/dc_offset_removed/mic"

    expected:
      sample_rate: 16000
      channels: 1
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000
      qos:
        depth: 10
        reliable: true
