fa_pan:
  ros__parameters:
    input_topic: "audio/channel_converted/mic"
    output_topic: "audio/panned/mic"

    pan:
      position: 0.0

    expected:
      sample_rate: 16000
      channels: 2
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000
      qos:
        depth: 10
        reliable: true
