fa_band_pass:
  ros__parameters:
    input_topic: "fa_band_pass/input"
    output_topic: "fa_band_pass/output"
    input_stream_id: "audio/sample_format/mic"
    output:
      stream_id: "audio/band_pass/mic"

    filter:
      low_cut_hz: 80.0
      high_cut_hz: 3400.0

    expected:
      sample_rate: 16000
      channels: 1
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000
      qos:
        depth: 10
        reliable: true
