fa_limiter:
  ros__parameters:
    input_topic: "fa_limiter/input"
    output_topic: "fa_limiter/output"
    input_stream_id: "audio/gain/mic"

    output:
      stream_id: "audio/limit/mic"

    threshold:
      linear: 1.0

    expected:
      sample_rate: 16000
      channels: 1
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"

    qos:
      depth: 10
      reliable: false

    diagnostics:
      qos:
        depth: 10
        reliable: false
      publish_period_ms: 1000
