fa_channel_convert:
  ros__parameters:
    input_topic: "fa_channel_convert/input"
    output_topic: "fa_channel_convert/output"
    input_stream_id: "audio/sample_format/mic"

    input:
      channels: 1

    output:
      channels: 2
      stream_id: "audio/channel_converted/mic"

    conversion:
      mode: "mono_to_stereo_duplicate"

    expected:
      sample_rate: 16000
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000
      qos:
        depth: 10
        reliable: true
