fa_resample:
  ros__parameters:
    target_sample_rate: 16000
    input:
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"
    output:
      encoding: "FLOAT32LE"
      bit_depth: 32

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000

    mic:
      enabled: true
      input_topic: "audio/frame"
      output_topic: "audio/resample16k/mic"

    ref:
      enabled: false
      input_topic: "audio/output/frame"
      output_topic: "audio/resample16k/ref"
