fa_resample:
  ros__parameters:
    target_sample_rate: 16000
    input:
      encoding: "FLOAT32LE"
      bit_depth: 32
      layout: "interleaved"
    output:
      encoding: "FLOAT32LE"
      bit_depth: 32

    qos:
      depth: 10
      reliable: false

    diagnostics:
      publish_period_ms: 1000
      qos:
        depth: 10
        reliable: true

    mic:
      enabled: true
      input_topic: "audio/frame"
      output_topic: "audio/resample16k/mic"
      input_stream_id: "audio/float32/mic"
      output:
        stream_id: "audio/preprocessed/mono16k"

    ref:
      enabled: false
      input_topic: "audio/output/frame"
      output_topic: "audio/resample16k/ref"
      input_stream_id: "audio/playback/main"
      output:
        stream_id: "audio/preprocessed/ref16k"
